//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleWrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExampleWrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OE/jm3XEM5J/HNka3GIDYADRdLV4O+P/N3bg5Zx5zKohBl2HTRrvudwM1AkHeCCSC74mjmzkDtLXfIoygvE9bKh5NZSMh1xoHtHV5T9OfBcTAZ/pEJmPNIX8QW10Hk/06ecaOcRYE4sOOBSg3h13tRgLVaTmOfgwykgYDA27QF/0e+AFdQn/fWhfQ2DKvOl4htLC/EWikeap1mYEntImcIs0p/P+BAFrTb88xEbHYjYgKz1DxtjNOC7Z4xGnz+K87xwEU7N/HbfhkjTa2+JpGXqkZR8J1Pz4ZlqHhlBDL9lb6zuocrkKd3WPGxPvbhv3Ar4Al/aEnZEKofp7ZEN2UpZoJcQq8QqzCfBdbQFPZmNiwXTBE7Iyj0O1/SphUr5FDN187g8Ce5BeaoC1tXRYycXwuXNzKRwXXBIdLTMN93R7QFRCY/ECqjsIBQmx5YA9adeGucZDVWXdtxNjD2I+6fAbZqdo603E6XbP6IxpKSHUZwpKuZPzFVrACtcfXUa/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelloWorldPacked {
            get {
                return ResourceManager.GetString("HelloWorldPacked", resourceCulture);
            }
        }
    }
}
